import type { Recipe } from "./schemas";

/**
 * Demo Mode sample data — realistic Persian home cooking.
 * Used when no AI provider is configured; the app is fully usable without keys.
 */
export const DEMO_RECIPES: Recipe[] = [
  {
    id: "ghormeh-sabzi",
    name: "قورمه‌سبزی",
    description: "خورشت کلاسیک ایرانی با سبزی تفت‌داده، لوبیا و گوشت؛ عطر لیمو عمانی نفس‌گیر است.",
    prepMinutes: 30,
    cookMinutes: 150,
    servings: 4,
    ingredients: [
      { id: "herbs", name: "سبزی قورمه‌سبزی", unit: "kilogram", qty: 0.4 },
      { id: "chicken", name: "گوشت یا مرغ", unit: "kilogram", qty: 0.5 },
      { id: "bean", name: "لوبیا چیتی", unit: "kilogram", qty: 0.2 },
      { id: "onion", name: "پیاز", unit: "count", qty: 3 },
      { id: "dried_lime", name: "لیمو عمانی", unit: "count", qty: 3 },
      { id: "turmeric", name: "زردچوبه", unit: "tablespoon", qty: 1 },
      { id: "tomato_paste", name: "رب گوجه", unit: "tablespoon", qty: 2 },
      { id: "rice", name: "برنج", unit: "kilogram", qty: 1.2 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 4 },
    ],
    steps: [
      "سبزی را پاک کنید، بشویید و ریز خرد کنید؛ در روغن زیاد تفت دهید تا کاملاً سرخ و برشته شود.",
      "پیاز خردشده را تفت دهید تا طلایی شود، زردچوبه و گوشت را اضافه کنید و تفت دهید تا رنگ گوشت تغییر کند.",
      "لوبیای خیس‌خورده، رب گوجه و سبزی سرخ‌شده را اضافه کنید و چند دقیقه با هم تفت دهید.",
      "آب جوش را به اندازه کافی اضافه کنید و خورشت را با حرارت ملایم حداقل دو ساعت بپزید.",
      "نیم‌ساعت تا آخر پخت، لیمو عمانی‌های سوراخ‌شده را اضافه کنید.",
      "با برنج دم‌کشیده سرو کنید.",
    ],
    tips: "سبزی باید واقعاً سرخ شود، نه فقط تفت؛ این راز رنگ و طعم قورمه‌سبزی است.",
    substitutions: ["گوشت گوسفندی را می‌توانید با مرغ جایگزین کنید", "لوبیا چیتی را با لوبیا قرمز هم می‌شود پخت"],
    tags: ["خورشت", "رسمی", "پرطرفدار"],
    mealTypes: ["lunch", "dinner"],
    isLeftover: false,
    estimatedCostToman: 1250000,
    difficulty: "متوسط",
    emoji: "🍲",
  },
  {
    id: "adas-polo",
    name: "عدس‌پلو",
    description: "پلوی خوش‌عطر با عدس و کشمش، معمولاً با خرما و گوشت چرخ‌کرده سرو می‌شود.",
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 4,
    ingredients: [
      { id: "rice", name: "برنج", unit: "kilogram", qty: 1.2 },
      { id: "lentil", name: "عدس", unit: "kilogram", qty: 0.5 },
      { id: "onion", name: "پیاز", unit: "count", qty: 2 },
      { id: "raisin", name: "کشمش", unit: "kilogram", qty: 0.15 },
      { id: "saffron", name: "زعفران", unit: "teaspoon", qty: 0.5 },
      { id: "turmeric", name: "زردچوبه", unit: "tablespoon", qty: 1 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 4 },
    ],
    steps: [
      "عدس را نیم‌پز کنید و آبکش کنید.",
      "برنج را با آب و نمک جوش بیاورید، عدس را اضافه کنید و با هم آبکش کنید.",
      "ته قابلمه روغن بریزید، کمی برنج بریزید و حلقه‌های پیاز و عدس را لایه‌ای اضافه کنید.",
      "زعفران دم‌کرده را روی برنج بدهید و با حرارت ملایم دم کنید.",
      "کشمش را با کره تفت داده و هنگام سرو روی پلو بگذارید.",
    ],
    tips: "برای ته‌دیگ طلایی، ته قابلمه را با مقدار کمی روغن بیشتر بپوشانید و حرارت را ملایم کنید.",
    substitutions: ["کشمش را می‌توانید با خرما جایگزین کنید"],
    tags: ["پلو", "اقتصادی", "راحت"],
    mealTypes: ["lunch", "dinner"],
    isLeftover: false,
    estimatedCostToman: 680000,
    difficulty: "آسان",
    emoji: "🍚",
  },
  {
    id: "koko-sabzi",
    name: "کوکو سبزی",
    description: "خوراک سبزی و تخم‌مرغ؛ سریع، اقتصادی و عالی برای صبحانه یا شام سبک.",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    ingredients: [
      { id: "herbs", name: "سبزی کوکو", unit: "kilogram", qty: 0.5 },
      { id: "egg", name: "تخم‌مرغ", unit: "count", qty: 5 },
      { id: "flour", name: "آرد", unit: "tablespoon", qty: 2 },
      { id: "turmeric", name: "زردچوبه", unit: "teaspoon", qty: 0.5 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 5 },
      { id: "walnut", name: "گردو خردشده", unit: "kilogram", qty: 0.05 },
    ],
    steps: [
      "سبزی را ریز خرد کنید یا چرخ کنید.",
      "تخم‌مرغ، آرد، زردچوبه، نمک و فلفل را با سبزی مخلوط کنید تا یکدست شود.",
      "روغن را در تابه داغ کنید، مایه را بریزید و با حرارت متوسط بپزید.",
      "یک طرف را بپزید، برگردانید و طرف دیگر را هم سرخ کنید.",
      "با نان و ماست سرو کنید.",
    ],
    tips: "مایه کوکو را قبل از پختن ۱۰ دقیقه استراحت بدهید تا سبزی آب نیندازد.",
    substitutions: ["گردو اختیاری است", "می‌توانید کمی سبزی خشک هم اضافه کنید"],
    tags: ["خوراک", "اقتصادی", "گیاهی"],
    mealTypes: ["breakfast", "dinner"],
    isLeftover: false,
    estimatedCostToman: 420000,
    difficulty: "آسان",
    emoji: "🥘",
  },
  {
    id: "joojeh-kabab-tabei",
    name: "جوجه کباب تابه‌ای",
    description: "جوجه‌های آبدار با زعفران و پیاز، بدون نیاز به منقل؛ مناسب شام هفته.",
    prepMinutes: 25,
    cookMinutes: 30,
    servings: 4,
    ingredients: [
      { id: "chicken", name: "سینه یا ران مرغ", unit: "kilogram", qty: 0.8 },
      { id: "onion", name: "پیاز", unit: "count", qty: 2 },
      { id: "lemon", name: "آبلیمو", unit: "tablespoon", qty: 2 },
      { id: "saffron", name: "زعفران", unit: "teaspoon", qty: 0.5 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 3 },
      { id: "rice", name: "برنج", unit: "kilogram", qty: 1.5 },
    ],
    steps: [
      "تکه‌های مرغ را با پیاز رنده‌شده، آبلیمو، زعفران، نمک و فلفل ۲ ساعت در یخچال مارینه کنید.",
      "روغن را در تابه داغ کنید و تکه‌های مرغ را بدون شلوغ کردن تابه کف تابه بچینید.",
      "هر طرف را حدود ۶ تا ۷ دقیقه با حرارت متوسط بپزید تا طلایی شود.",
      "بقیه ماریناد را وسط پخت اضافه کنید تا مرغ آبدار بماند.",
      "با برنج یا نان و گوجه کبابی سرو کنید.",
    ],
    tips: "تابه را شلوغ نکنید؛ مرغ باید سرخ شود، نه آب بجوشد.",
    substitutions: ["ماست را به ماریناد اضافه کنید تا مرغ نرم‌تر شود"],
    tags: ["کباب", "پروتئین بالا"],
    mealTypes: ["lunch", "dinner"],
    isLeftover: false,
    estimatedCostToman: 890000,
    difficulty: "آسان",
    emoji: "🍗",
  },
  {
    id: "koko-sibzamini",
    name: "کوکو سیب‌زمینی",
    description: "خوراک محبوب سیب‌زمینی و تخم‌مرغ؛ با نان تازه یک شام کامل می‌شود.",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    ingredients: [
      { id: "potato", name: "سیب‌زمینی", unit: "kilogram", qty: 0.8 },
      { id: "egg", name: "تخم‌مرغ", unit: "count", qty: 4 },
      { id: "turmeric", name: "زردچوبه", unit: "teaspoon", qty: 0.5 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 5 },
    ],
    steps: [
      "سیب‌زمینی را آب‌پز کنید، پوست بکنید و رنده کنید.",
      "با تخم‌مرغ، زردچوبه، نمک و فلفل مخلوط کنید.",
      "در تابه روغن داغ، مایه را به ضخامت یک انگشت پهن کنید.",
      "هر طرف را ۵ تا ۶ دقیقه سرخ کنید تا برشته شود.",
    ],
    tips: "سیب‌زمینی را حتماً بعد از آب‌پز کمی خنک کنید تا مایه آب نیندازد.",
    substitutions: ["می‌توانید کمی زرشک یا کشمش هم اضافه کنید"],
    tags: ["خوراک", "اقتصادی"],
    mealTypes: ["dinner", "snack"],
    isLeftover: false,
    estimatedCostToman: 330000,
    difficulty: "آسان",
    emoji: "🥔",
  },
  {
    id: "omlet-gojeh",
    name: "املت گوجه",
    description: "صبحانه‌ی همیشگی ایرانی؛ ساده، سریع و با نان سنگک فوق‌العاده است.",
    prepMinutes: 5,
    cookMinutes: 10,
    servings: 2,
    ingredients: [
      { id: "tomato", name: "گوجه", unit: "count", qty: 3 },
      { id: "egg", name: "تخم‌مرغ", unit: "count", qty: 4 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 2 },
      { id: "turmeric", name: "زردچوبه", unit: "teaspoon", qty: 0.3 },
    ],
    steps: [
      "گوجه‌های خردشده را با روغن و کمی زردچوبه تفت دهید تا آبش کشیده شود.",
      "تخم‌مرغ‌ها را اضافه کنید و هم بزنید تا تکه‌های نرم درست شود.",
      "نمک و فلفل بزنید و با نان داغ سرو کنید.",
    ],
    tips: "برای املت غلیظ‌تر، آب گوجه را کاملاً بکشید و بعد تخم‌مرغ بزنید.",
    substitutions: ["می‌توانید فلفل دلمه یا سوسیس هم اضافه کنید"],
    tags: ["صبحانه", "سریع"],
    mealTypes: ["breakfast"],
    isLeftover: false,
    estimatedCostToman: 180000,
    difficulty: "آسان",
    emoji: "🍳",
  },
  {
    id: "adasi",
    name: "عدسی",
    description: "خوراک گرم و مقوی عدس؛ ناهار پرمغذی برای روزهای سرد یا شام سبک.",
    prepMinutes: 10,
    cookMinutes: 50,
    servings: 4,
    ingredients: [
      { id: "lentil", name: "عدس", unit: "kilogram", qty: 0.4 },
      { id: "onion", name: "پیاز", unit: "count", qty: 1 },
      { id: "potato", name: "سیب‌زمینی", unit: "count", qty: 2 },
      { id: "turmeric", name: "زردچوبه", unit: "teaspoon", qty: 1 },
      { id: "tomato_paste", name: "رب گوجه", unit: "tablespoon", qty: 1 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 2 },
    ],
    steps: [
      "عدس را شسته و با آب و زردچوبه بگذارید بپزد.",
      "پیاز خردشده را تفت دهید تا طلایی شود و به عدس اضافه کنید.",
      "سیب‌زمینی مکعبی‌شده و رب گوجه را اضافه کنید.",
      "حدود ۴۰ دقیقه با حرارت ملایم بپزید تا غلیظ شود.",
      "با آب‌لیمو و نان سرو کنید.",
    ],
    tips: "در پایان پخت کمی دارچین بزنید؛ عطرش را دوچندان می‌کند.",
    substitutions: ["سیب‌زمینی اختیاری است"],
    tags: ["خوراک", "گیاهی", "اقتصادی"],
    mealTypes: ["lunch", "dinner"],
    isLeftover: false,
    estimatedCostToman: 260000,
    difficulty: "آسان",
    emoji: "🥣",
  },
  {
    id: "makaroni-irani",
    name: "ماکارونی ایرانی",
    description: "ماکارونی با سس گوشت و ته‌دیگ طلایی؛ محبوب بچه‌ها و منصفانه با بودجه.",
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 4,
    ingredients: [
      { id: "pasta", name: "ماکارونی", unit: "package", qty: 1 },
      { id: "ground_beef", name: "گوشت چرخ‌کرده", unit: "kilogram", qty: 0.3 },
      { id: "onion", name: "پیاز", unit: "count", qty: 1 },
      { id: "tomato_paste", name: "رب گوجه", unit: "tablespoon", qty: 3 },
      { id: "turmeric", name: "زردچوبه", unit: "teaspoon", qty: 0.5 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 4 },
    ],
    steps: [
      "پیاز را تفت دهید، گوشت را اضافه کنید و بپزید تا تغییر رنگ دهد.",
      "رب گوجه، نمک، فلفل و کمی آب اضافه کنید؛ سس را ۱۰ دقیقه بجوشانید.",
      "ماکارونی را در آب جوش نمک‌دار نیم‌پز کنید و آبکش کنید.",
      "ته قابلمه روغن بدهید، ماکارونی و سس را لایه‌ای بریزید.",
      "با حرارت ملایم ۳۰ دقیقه دم کنید تا ته‌دیگ طلایی شود.",
    ],
    tips: "برای ته‌دیگ بهتر، کمی ماست یا زرده تخم‌مرغ به روغن ته قابلمه بزنید.",
    substitutions: ["گوشت را می‌توانید با سویا جایگزین کنید"],
    tags: ["خانوادگی", "محبوب بچه‌ها"],
    mealTypes: ["lunch", "dinner"],
    isLeftover: false,
    estimatedCostToman: 540000,
    difficulty: "آسان",
    emoji: "🍝",
  },
  {
    id: "mirza-ghasemi",
    name: "میرزا قاسمی",
    description: "بادمجان دودی با سیر، گوجه و تخم‌مرغ؛ خوراک شمالی با عطر بی‌نظیر.",
    prepMinutes: 20,
    cookMinutes: 30,
    servings: 4,
    ingredients: [
      { id: "eggplant", name: "بادمجان", unit: "kilogram", qty: 1 },
      { id: "egg", name: "تخم‌مرغ", unit: "count", qty: 3 },
      { id: "garlic", name: "سیر", unit: "clove", qty: 5 },
      { id: "tomato", name: "گوجه", unit: "count", qty: 2 },
      { id: "oil", name: "روغن", unit: "tablespoon", qty: 4 },
      { id: "kashek", name: "کشک", unit: "tablespoon", qty: 2 },
    ],
    steps: [
      "بادمجان‌ها را روی شعله یا فر کبابی کنید، پوست بگیرید و خرد کنید.",
      "سیر خردشده را در روغن تفت دهید تا عطرش بلند شود.",
      "گوجه‌های خردشده را اضافه کنید تا بپزند.",
      "بادمجان‌ها را اضافه کنید و چند دقیقه تفت دهید.",
      "تخم‌مرغ‌ها را در مایه بزنید تا سفت شوند؛ کشک را آخر کار اضافه کنید.",
    ],
    tips: "بادمجان کبابی (نه آب‌پز) تفاوت طعم را می‌سازد.",
    substitutions: ["کشک اختیاری است", "می‌توانید به جای کبابی کردن، بادمجان را فر کنید"],
    tags: ["شمالی", "خوراک"],
    mealTypes: ["dinner"],
    isLeftover: false,
    estimatedCostToman: 380000,
    difficulty: "آسان",
    emoji: "🍆",
  },
  {
    id: "sandwich-morgh",
    name: "ساندویچ مرغ باقی‌مانده",
    description: "استفاده هوشمندانه از مرغ مانده؛ شام سریع و بدون خرید اضافه.",
    prepMinutes: 10,
    cookMinutes: 5,
    servings: 2,
    ingredients: [
      { id: "chicken", name: "مرغ پخته باقی‌مانده", unit: "kilogram", qty: 0.2 },
      { id: "bread", name: "نان", unit: "count", qty: 2 },
      { id: "tomato", name: "گوجه", unit: "count", qty: 1 },
      { id: "yogurt", name: "ماست", unit: "tablespoon", qty: 2 },
    ],
    steps: [
      "مرغ باقی‌مانده را ریش‌ریش کنید و کمی با روغن و زردچوبه سرخ کنید.",
      "با ماست و نمک مخلوط کنید.",
      "داخل نان با گوجه و سبزی بگذارید و در ساندویچ‌ساز گرم کنید.",
    ],
    tips: "یک قاشق سس سیر خانگی طعم ساندویچ را حرفه‌ای می‌کند.",
    substitutions: ["به جای ماست، کمی پنیر هم می‌شود استفاده کرد"],
    tags: ["باقی‌مانده", "سریع"],
    mealTypes: ["dinner"],
    isLeftover: true,
    estimatedCostToman: 60000,
    difficulty: "آسان",
    emoji: "🥪",
  },
];

export const DEMO_RECIPE_MAP: Record<string, Recipe> = Object.fromEntries(
  DEMO_RECIPES.map((r) => [r.id, r]),
);
